[build-system]
requires = [ "flot>=0.7.0" ]
build-backend = "flot.buildapi"

[project]
name = "packagedcode"
version = "32.1.0"
description = "PackagedCode is a library to parse and normalize package manifests, lockfiles and dependencies for all type of app and system packages and report them by PURL."
license = { text = "Apache-2.0 AND CC-BY-4.0 AND LicenseRef-scancode-other-permissive AND LicenseRef-scancode-other-copyleft" }
# TODO consider a readme?
# readme = "README.rst"
requires-python = ">=3.8"
authors = [
    { name = "nexB. Inc. and others", email = "info@aboutcode.org" },
]
keywords = [
    "open source",
    "scan",
    "license",
    "package",
    "dependency",
    "copyright",
    "filetype",
    "author",
    "extract",
    "licensing",
    "sca",
    "SBOM",
    "spdx",
    "cyclonedx",
    "package-url",
    "purl",
]

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development",
    "Topic :: Utilities",
]

dependencies = [
    "attrs >= 18.1,!=20.1.0;python_version<'3.11'",
    "attrs >= 22.1.0;python_version>='3.11'",
    "Beautifulsoup4 >= 4.0.0",
    "boolean.py >= 4.0",
    "chardet >= 3.0.0",
    "click >= 6.7, !=7.0",
    "colorama >= 0.3.9",
    "commoncode >= 31.0.3",
    "container-inspector >= 31.0.0",
    "debian-inspector >= 31.1.0",
    "dparse2 >= 0.7.0",
    "fasteners",
    "fingerprints >= 0.6.0",
    "ftfy >=  6.0.0",
    "gemfileparser2 >= 0.9.0",
    "html5lib",
    "importlib_metadata",
    "intbitset >= 3.0.2",
    "jaraco.functools",
    "javaproperties >= 0.5",
    "jinja2 >= 2.7.0",
    "jsonstreams >= 0.5.0",
    "license_expression >= 30.1.1",
    "lxml >= 4.9.2",
    "MarkupSafe >= 2.1.2",
    "packageurl_python >= 0.9.0",
    "packvers >= 21.0.0",
    # use temp advanced patched release
    "parameter-expansion-patched >= 0.3.1",
    "pdfminer.six >= 20200101",
    "pefile >= 2020.1.1",
    "pip-requirements-parser >= 32.0.1",
    "pkginfo2 >= 30.0.0",
    "pluggy >= 1.0.0",
    "plugincode >= 32.0.0",
    "publicsuffix2",
    "pyahocorasick >= 2.0.0",
    "pygmars >= 0.7.0",
    "pygments",
    "pymaven_patch >= 0.2.8",
    "requests >= 2.7.0",
    "saneyaml >= 0.6.0",
    "spdx_tools == 0.8.2",
    "text_unidecode >= 1.0",
    "toml >= 0.10.0",
    "urlpy",
    "xmltodict >= 0.11.0",
    "zipp >= 3.0.0; python_version < \"3.9\"",
    "typecode >= 30.0.1",
    "typecode[full] >= 30.0.1",
]

[project.urls]
Homepage = "https://github.com/nexB/scancode-toolkit"


[project.optional-dependencies]
# linux-only package handling
packages = [
    "rpm_inspector_rpm >= 4.16.1.3; platform_system == 'Linux'",
    "regipy >= 3.1.0; platform_system == 'Linux'",
    "packagedcode_msitools >= 0.101.210706; platform_system == 'Linux'",
]


[tool.flot]
wheel_path_prefixes_to_strip = [ "src" ]

includes = [
    "src/packagedcode/**/*",
]

excludes = [
    # Python compiled files
    "**/*.py[cod]",
    "**/*.egg-info",
    # Various junk and temp files
    "**/.DS_Store",
    "**/*~",
    "**/.*.sw[po]",
    "**/.ve",
    "**/*.bak",
    "**/.ipynb_checkpoints",
]

metadata_files = [
    "*.LICENSE",
    "NOTICE",
    "AUTHORS.rst",
    "CHANGELOG.rst",
    "CODE_OF_CONDUCT.rst",
]

editable_paths = [ "src", "tests" ]

sdist_extra_includes = [
    "tests/packagedcode/*",
    ".gitattributes",
    ".gitignore",
    "*.LICENSE",
    "NOTICE",
    "*.ABOUT",
    "*packagedcode*.toml",
    "*.yml",
    "*.rst",
    "*.py",

    "requirements*",
]
